name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check formatting
        run: 'diff riskychat.c <(clang-format riskychat.c)'
      - name: Build
        run: cc -O2 -std=c89 -Wall -Werror -oriskychat riskychat.c
      - name: Test
        run: sh test.sh
  tag_release_and_deploy:
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    needs: [lint_and_test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install musl-gcc
        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad
        with:
          packages: musl-tools musl-dev
          version: 1.0
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Create a new tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Build
        run: musl-gcc -static -O2 -oriskychat riskychat.c
      - name: Prepare deployment
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
